server:
  port: 8441


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sports?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#    配置上传的文件大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 40MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.blingwei.musicService.pojo
  config-location: classpath:configs/mybatis-config.xml


